# Generated by Django 3.0.7 on 2020-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
