# Generated by Django 3.0.7 on 2020-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='modelcode',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
